django_app/book_store/urls.py
from django.conf.urls import url

from . import views

app_name = 'books'
urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^sell/list$', views.book_sell_list, name='book_sell_list'),
    url(r'^sell/register$', views.book_sell_register, name='book_sell_register'),
    url(r'^sell/register/save$', views.book_sell_register_save, name='book_sell_register_save'),
    url(r'^bucket/(?P<transaction_pk>\d+)/save$', views.book_bucket_save, name='book_bucket_save'),
    url(r'^bucket/list$', views.book_bucket_list, name='book_bucket_list'),
    url(r'^buy/list$', views.book_buy_list, name='book_buy_list'),
    url(r'^book_search/$', views.book_search, name='book_search'),
    url(r'^book_bucket/$', views.book_bucket, name='book_bucket'),
    url(r'^detail/(?P<book_pk>\d+)/$', views.book_detail, name='book_detail'),

    url(r'^(?P<post_pk>\d+)/transaction/comment/$', views.transaction_comment_create, name='transaction_comment_create'),
]

django_app/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django_messages.views import *
from django_app.member.forms import NewComposeForm
# from member.forms import NewComposeForm
from django.conf.urls.static import static
from django_app.member import views
# from member import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^book/', include('book_store.urls', namespace="book_store")),
    url(r'^member/', include('member.urls', namespace="member")),
    url(r'^messages/compose/$', compose, {'form_class': NewComposeForm,}, name='messages_compose'),
    url(r'^messages/', include('django_messages.urls')),
    # url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^$', views.login),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
urlpatterns += static('/static/', document_root='project/.static_root')
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_app/member/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from . import views


app_name = 'member'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),

    # social login
    url(r'^login/facebook/$', views.facebook_login, name='facebook_login'),
    url(r'^login/kakao/$', views.kakao_login, name='kakao_login'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

django_app/member/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager as DefaultUserManager


class UserManager(DefaultUserManager):
    def get_or_create_facebook_user(self, user_info):
        username = '{}_{}_{}'.format(
            self.model.USER_TYPE_FACEBOOK,
            settings.FACEBOOK_APP_ID,
            user_info['id'],
        )

        user, user_created = self.get_or_create(
            username=username,
            user_type=self.model.USER_TYPE_FACEBOOK,
            defaults={
                'email': user_info.get('email', ''),
            }
        )
        return user

    def get_or_create_kakao_user(self, user_info):
        print('id' in user_info)
        username = '{}_{}_{}'.format(
            self.model.USER_TYPE_KAKAO,
            settings.KAKAO_APP_ID,
            user_info['id'],
        )

        user, user_created = self.get_or_create(
            username=username,
            user_type=self.model.USER_TYPE_KAKAO,
            defaults={
                'email': user_info.get('kaccount_email', ''),
                # 'nickname': user_info.get('nickname', '')
            }
        )
        return user


class User(AbstractUser):
    USER_TYPE_DJANGO = 'd'
    USER_TYPE_FACEBOOK = 'f'
    USER_TYPE_KAKAO = 'k'
    USER_TYPE_CHOICES = (
        (USER_TYPE_DJANGO, 'Django'),
        (USER_TYPE_FACEBOOK, 'Facebook'),
        (USER_TYPE_KAKAO, 'kakao'),
    )

    objects = UserManager()

    # profile_img = models.ImageField(blank=True)
    email = models.EmailField(null=True, blank=True)
    nickname = models.CharField(max_length=30)

    # 자주 검색하는 테이블일 경우 인덱스를 거는 것이 좋다

    # 유저타입. 기본은 Django, 페이스북 로그인 시 USER_TYPE_FACEBOOK 값을 갖음
    user_type = models.CharField(max_length=1, choices=USER_TYPE_CHOICES, default=USER_TYPE_DJANGO)

django_app/member/forms/login.py
from django import forms
from django.contrib.auth import authenticate


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)

    username = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Username',
                'class': 'input-id',
            }
        )
    )
    password = forms.CharField(
        label='',
        widget=forms.PasswordInput(
            attrs={
            'placeholder': 'Password',
            'class': 'input-password',
            }
        )
    )

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        user = authenticate(
            username=username,
            password=password,
        )
        if user is not None:
            self.cleaned_data['user'] = user
        else:
            raise forms.ValidationError(
                '. 다시 로그인하시거나, 회원가입해주세요.'
            )
        return self.cleaned_data

django_app/member/forms/message.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django_messages.forms import ComposeForm
from django_messages.models import Message
if "pinax.notifications" in settings.INSTALLED_APPS and getattr(settings, 'DJANGO_MESSAGES_NOTIFY', True):
    from pinax.notifications import models as notification
else:
    notification = None


User = get_user_model()

class NewComposeForm(ComposeForm):
    recipient = forms.ModelChoiceField(label='받아랏!', queryset=User.objects.all())

    def save(self, sender, parent_msg=None):
        recipients = self.cleaned_data['recipient']
        subject = self.cleaned_data['subject']
        body = self.cleaned_data['body']
        message_list = []
        msg = Message(
            sender=sender,
            recipient=recipients,
            subject=subject,
            body=body,
        )
        if parent_msg is not None:
            msg.parent_msg = parent_msg
            parent_msg.replied_at = timezone.now()
            parent_msg.save()
        msg.save()
        message_list.append(msg)
        if notification:
            if parent_msg is not None:
                notification.send([sender], "messages_replied", {'message': msg,})
                notification.send([r], "messages_reply_received", {'message': msg,})
            else:
                notification.send([sender], "messages_sent", {'message': msg,})
                notification.send([r], "messages_received", {'message': msg,})
        return message_list

django_app/member/forms/signup.py
import re

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email', 'nickname')  # NOTE: User

django_app/member/views/user.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

def profile(request):
    return render(request, 'member/profile.html')

django_app/templates/member/login.html
{% load static %}

<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>BongDal Login</title>

  <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">

  <link href='https://fonts.googleapis.com/css?family=Gochi Hand' rel='stylesheet'>
  <link href='https://fonts.googleapis.com/css?family=Walter Turncoat' rel='stylesheet'>
</head>
<body>
  <div class="container">
    <div class="top-bar">
      <div class="logo">
        <a href="{% url 'books:main' %}">
          BongDal
        </a>
      </div>
      <div class="do">
        <a href="{% url 'member:signup' %}">
          계정만들기
        </a>
        <a href="{% url 'member:login' %}">
          로그인
        </a>
      </div>
    </div>
    <div class="content">
      <div class="do-login">
        <div class="login-title">
          <h2>로그인</h2>
        </div>
        <nav>
            <div class="login-input">
              <form action="" method="POST">
                {% csrf_token %}
                {% include 'include/member-field-set.html' with form=form %}
                <button type="submit" class="btn-mint">로그인</button>
              </form>
              <a href="{% url 'member:signup' %}">
                <button class="btn-pink">회원가입</button>
              </a>
            </div>
        </nav>
        <div class="facebook">
          <p>
            --------------- 또는 ---------------
          </p>
            <a href="https://www.facebook.com/v2.9/dialog/oauth?client_id={{ facebook_app_id }}&redirect_uri={{ site_url }}{% url 'member:facebook_login' %}" class="btn-facebook">
              페이스북 로그인
            </a>
            <a href="https://kauth.kakao.com/oauth/authorize?client_id={{ kakao_app_id }}&redirect_uri={{ redirect_uri }}&response_type=code" class="btn-kakao">
              카카오 로그인
            </a>
          <p>
            계정이 없나요? <a href="#">계정 만들기</a>
          </p>
          비밀번호가 기억나지 않으세요? <a href="#">비밀번호 재설정</a>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

django_app/templates/member/profile.html
{% extends 'common/base.html' %}
{% block content %}
<h1>프로필</h1>
<ul>
    <li>username : {{ user.username }}</li>
    <li>nickname : {{ user.nickname }}</li>
    <li>emai : {{ user.email }}</li>
</ul>
{% endblock %}

django_app/templates/member/signup.html
{% extends 'common/base.html' %}
{% block content %}
    <h1>회원가입</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="회원가입">
    </form>
{% endblock %}