django_app/book_store/urls.py
from django.conf.urls import url

from . import views

app_name = 'books'
urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^sell/list$', views.book_sell_list, name='book_sell_list'),
    url(r'^sell/register$', views.book_sell_register, name='book_sell_register'),
    url(r'^sell/register/save$', views.book_sell_register_save, name='book_sell_register_save'),
    url(r'^bucket/(?P<transaction_pk>\d+)/save$', views.book_bucket_save, name='book_bucket_save'),
    url(r'^bucket/list$', views.book_bucket_list, name='book_bucket_list'),
    url(r'^buy/list$', views.book_buy_list, name='book_buy_list'),
    url(r'^book_search/$', views.book_search, name='book_search'),
    url(r'^book_bucket/$', views.book_bucket, name='book_bucket'),
    url(r'^detail/(?P<book_pk>\d+)/$', views.book_detail, name='book_detail'),

    url(r'^(?P<post_pk>\d+)/transaction/comment/$', views.transaction_comment_create, name='transaction_comment_create'),
]

django_app/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django_messages.views import *
from django_app.member.forms import NewComposeForm
# from member.forms import NewComposeForm
from django.conf.urls.static import static
from django_app.member import views
# from member import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^book/', include('book_store.urls', namespace="book_store")),
    url(r'^member/', include('member.urls', namespace="member")),
    url(r'^messages/compose/$', compose, {'form_class': NewComposeForm,}, name='messages_compose'),
    url(r'^messages/', include('django_messages.urls')),
    # url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^$', views.login),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
urlpatterns += static('/static/', document_root='project/.static_root')
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_app/book_store/models/book.py
from django.conf import settings
from django.db import models
from django_extensions.db.models import TimeStampedModel


class Book(TimeStampedModel):
    """책 정보"""
    image_url = models.CharField("이미지url", max_length=240)
    title = models.CharField("제목", max_length=48)
    intro = models.TextField("소개", blank=True)
    writer = models.CharField("저자", max_length=36)
    price = models.IntegerField("정가")
    isbn = models.CharField("isbn", max_length=100, unique=True)
    publisher = models.CharField("출판사", max_length=40)
    publication_date = models.DateField("출판일")

    def __str__(self):
        return "{} {}".format(self.title, self.writer)


class Transaction(TimeStampedModel):
    """거래기록"""
    book = models.ForeignKey(Book)
    seller = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="seller_set", verbose_name="판매자", null=True, default=None, blank=True)
    buyer = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="buyer_set", verbose_name="구매자", null=True, default=None, blank=True)
    is_successed = models.BooleanField("거래성사", default=False)
    sell_price = models.IntegerField("판매가")


class BookLike(TimeStampedModel):
    """책에 대한 좋아요"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    book_info = models.ForeignKey(Book)


class Category(models.Model):
    pass


class BookBuyBucket(TimeStampedModel):
    """장바구니"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    transaction = models.ForeignKey(
        Transaction,
    )

    class Meta:
        unique_together = (("user", "transaction"),)


class BookSellBucket(TimeStampedModel):
    """판매자 판매 목록"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    book = models.ForeignKey(
        Book,
    )

django_app/book_store/views/book.py
from django.contrib.auth import get_user_model
from django.db import IntegrityError
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from ..forms.transaction import SellBookForm
from ..models import Transaction
from ..models import Book
from ..models import BookBuyBucket
from ..forms import SearchForm

from ..api import get_book_info, register_book

User = get_user_model()


def main(request):
    books = Book.objects.all()
    context = {
        'books': books,
        'search': SearchForm(),
    }
    return render(request, 'books/main.html', context)


def book_detail(request, book_pk):
    book = Book.objects.get(pk=book_pk)
    context = {
        'book': book,
    }
    return render(request, 'books/book_detail.html', context)


def book_search(request):

    # data 를 POST 요청으로 처리해서 form 변수에 할당
    form = SearchForm(data=request.POST)

    # is_valid() 를 통해 data clean 과정을 거쳐 폼 유효성을 검사한다.
    if form.is_valid():

        # 사용자가 입력한 순수 검색어를 q 에 할당
        q = form.cleaned_data['q_search']

        # BookInfo 테이블의 title, writer, publisher 필드에 q 가 속한 레코드를 book_lists 에 할당
        book_lists = Book.objects.filter(
            Q(Q(title__contains=q) | Q(writer__contains=q)) | Q(publisher__contains=q),
        )

        # 템플릿에 보이기 위한 필요한 데이터를 인자로 전달
        context = {
            'q': q,
            'book_lists': book_lists,
            'book_count': book_lists.count(),
            'search': SearchForm(),
        }

        return render(request, 'books/book_list.html', context)


def book_bucket(request):
    if request.method == 'POST':

        # input 태그 name="book_id" 에 해당하는 value 를 book_id 에 할당
        book_id = request.POST['book_id']

        # book_id 에 해당하는 BookInfo 테이블의 레코드를 book_info 에 할당
        book_info = get_object_or_404(Book, pk=book_id)

        # BookBuyBucket 을 역참조하여 로그인 한 유저가 선택한 책 정보가 담긴 레코드 생성
        # 장바구니는 책을 중복할 수 있으므로 get_or_create 가 아닌 create 활용
        book_info.bookbuybucket_set.create(
            user=request.user,
            book=book_info,
        )

        # book_lists = book_info.BookBuyBucket_set.filter(user_id=request.user.id)
        # 질문) 아래 코드와 뭐가 다른건지 모르겠다.

        # BookBuyBucket 테이블에서 user id 에 해당하는 레코드를 전부 book_lists 에 할당(객체의 iterable 형태)
        book_lists = BookBuyBucket.objects.filter(user_id=request.user.id)

        # 템플릿에 전달할 인자인 books 선언
        books = []

        # iterable 형태인 book_lists 를 for 문으로 분리시키고,
        for book_list in book_lists:

            # 분리된 BookBuyBucket 레코드의 book_id 에 해당하는 BookInfo 의 정보를 순차적으로 books 에 append
            books.append(Book.objects.get(pk=book_list.book_id))

        context = {
            'books': books,
        }
        return render(request, 'books/book_bucket.html', context)
    else:
        book_lists = BookBuyBucket.objects.filter(user_id=request.user.id)

        books = []

        for book_list in book_lists:
            books.append(Book.objects.get(pk=book_list.book_id))

        context = {
            'books': books,
        }
        return render(request, 'books/book_bucket.html', context)


def book_sell_list(request):
    sell_transactions = Transaction.objects.filter(
        is_successed=False, buyer__isnull=True, seller__isnull=False
    ).prefetch_related('book')
    return render(request, 'books/sell_list.html', {'sell_transactions': sell_transactions})


def book_buy_list(request):
    pass


def book_bucket_save(request, transaction_pk):
    '''
    책 찜하기
    :param request: Request
    :param transaction_pk: Transaction
    '''
    transaction = get_object_or_404(
        Transaction, pk=transaction_pk)
    try:
        BookBuyBucket.objects.create(
            user=request.user, transaction=transaction)
    except IntegrityError:
        return redirect('books:book_sell_list')
    return redirect('books:book_bucket_list')


def book_bucket_list(request):
    '''
    찜한 책 리스트
    :param request: Request
    '''
    items = BookBuyBucket.objects.filter(
        user=request.user
    ).prefetch_related(
        'transaction', 'transaction__book'
    )
    return render(request, 'books/book_bucket.html', {'items': items})


def book_sell_register(request):
    keyword = request.GET.get('keyword')
    items = None
    if keyword:
        items = get_book_info(keyword)
    datas = []
    if items:
        for item in items:
            book = register_book(isbn=item['isbn'])[1]
            form = SellBookForm(initial={'book': book})
            datas.append([item, form])
    return render(request, 'books/book_sell_register.html', {'datas': datas})

def book_sell_register_save(request):
    if request.method == 'POST':
        form = SellBookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            book.seller = request.user
            book.save()
        return redirect('books:book_sell_list')

django_app/templates/books/book_bucket.html
{% extends 'common/base.html' %}

{% block content %}
    <h1>찜한 책</h1>
    <ul>
    {% for item in items %}
    <li><img src="{{ item.transaction.book.image_url }}"></li>
        <li>{{ item.transaction.book.title }}</li>
        <li>{{ item.transaction.book.writer }}</li>
        <li>{{ item.transaction.book.publisher }}</li>
        <li>정가 : {{ item.transaction.book.price }}</li>
        <li>판매가격 : {{item.transaction.sell_price }}원</li>
    {% endfor %}
    </ul>
{% endblock %}

django_app/templates/books/book_detail.html
{% extends 'common/base.html' %}

{% block content %}

<section>
<img src="{{ book.image_url }}" alt="표지 이미지">
<div>제목</div>
<div>{{ book.title }}</div>
<div>소개</div>
<div>{{ book.intro }}</div>
<div>저자</div>
<div>{{ book.writer }}</div>
<div>정가</div>
<div>{{ book.price }}</div>
<div>출판사</div>
<div>{{ book.publisher }}</div>
<div>출판일</div>
<div>{{ book.publication_date }}</div>
<div>isbn</div>
<div>{{ book.isbn }}</div>
<div>남은수량</div>

    {% if book.left_over %}
        <div>{{ book.left_over }}</div>
        <form action="{% url 'books:book_buy' book.id %}" method="POST">
            {% csrf_token %}
            <button type="submit">구매하기</button>
        </form>
    {% else %}
        <div>재고가 없습니다</div>
    {% endif %}
<form action="{% url 'books:book_sell' book.id %}" method="POST">
    {% csrf_token %}

    <button type="submit">판매하기</button>
</form>

</section>
{% endblock %}

django_app/templates/books/book_list.html
{% extends 'common/base.html' %}

{% block content %}

<div class="book_count">
    "<a href="#">{{ q }}</a>"
    의 검색 결과 : {{ book_count }} 개
</div>

<form action="{% url 'books:book_bucket' %}" method="POST">
    {% csrf_token %}
    <button type="submit">장바구니에 담기</button>
    <a href="#">최근등록순</a>
    <a href="#">판매량순</a>
    {% for book_list in book_lists %}
        <ul>
            <li>
                <div class="book-info">
                    <div class="book-img">
                        <input type="checkbox" name="book_id", value="{{ book_list.pk }}"/>
                        <img src="{{ book_list.image_url }}">
                    </div>
                    <div class="book_description">
                        <p class="book-title">{{ book_list.title }}</p>
                        <span>
                            <a href="#">
                                {{ book_list.writer }}
                            </a> |
                            <a href="#">
                                {{ book_list.publisher }}
                            </a> | {{ book_list.publication }}
                        </span>
                    </div>
                </div>
            </li>
        </ul>
    {% endfor %}
</form>
{% endblock %}

django_app/templates/books/book_list_test.html
{% extends 'common/base.html' %}

{% block content %}
<div class="book_count">
    "<a href="#">{{ q }}</a>"
    의 검색 결과 : {{ book_count }} 개
</div>
{% for book_list in book_lists %}
    <ul>
        <li>
            <div class="book-info">
                <div class="book-img">
                    <img src="{{ book_list.image.url }}">
                </div>
                <div class="book_description">
                    <p class="book-title">{{ book_list.title }}</p>
                    <span>
                        <a href="#">
                            {{ book_list.writer }}
                        </a> |
                        <a href="#">
                            {{ book_list.publisher }}
                        </a> | {{ book_list.publication }}
                    </span>
                </div>
            </div>
        </li>
    </ul>
{% endfor %}
{% endblock %}

django_app/templates/books/book_sell.html
{% extends 'common/base.html' %}

{% block content %}
<section>
    <img src="{{ book.image_url }}">
    <div>{{ book.title }} | {{ book.writer }} | {{ book.publisher }}</div>
    <div>판매희망 가격 : </div>
    {{ price }}
{#    판매자정보로 보내기#}
    <button type="submit">판매 등록하기</button>
</section>
{% endblock %}

django_app/templates/books/book_sell_register.html
{% extends 'common/base.html' %}

{% block content %}
    <form action="" method="get">
        <input type="text" name="keyword">
        <input type="submit">
    </form>

    {% if datas %}
        {% for book, form in datas %}
            {% include 'include/book.html' %}
            <form action="{% url 'books:book_sell_register_save' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit">
            </form>
        {% endfor %}
    {% endif %}
{% endblock %}

django_app/templates/books/book_sell_register_price.html
{% extends 'common/base.html' %}

{% block content %}
    <form action="" method="get">
        <input type="text" name="keyword">
        <input type="submit">
    </form>

        {% include 'include/book.html' %}
{% endblock %}

django_app/templates/books/comment_test.html
<form action="" method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">작성</button>
</form>

django_app/templates/books/main.html
{% extends 'common/base.html' %}

{% block content %}

    <div class="moving-books">
        {% include 'include/moving-book-list.html' %}
    </div>
    <div class="book-list">
        {% for book in books %}
        <ul>
            <li>
                <div class="book-info">
                    <div class="book-img">
                        <a href="{% url "book_store:main"%}"><img src="{{ book.image_url }}">
                        </a>
                    </div>
                    <div class="book_description">
                        <p class="book-title">{{ book.title }}</p>
                        <span>
                            <a href="#">
                                {{ book.writer }}
                            </a> |
                            <a href="#">
                                {{ book.publisher }}
                            </a> | {{ book.publication }}
                        </span>
                    </div>
                </div>
            </li>
        </ul>
        {% endfor %}
    </div>
{% endblock %}

django_app/templates/books/register_test.html
<form action="" method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">등록하기</button>
</form>

django_app/templates/books/sell_list.html
{% extends 'common/base.html' %}

{% block content %}
    <h1>판매중 도서 목록</h1>
    <h3><a href="{% url 'books:book_sell_register' %}">판매도서 등록</a></p></h3>
    <ul>
{% for transaction in sell_transactions %}
    <li><img src="{{ transaction.book.image_url }}" alt=""></li>
    <li>{{ transaction.book.title }}</li>
    <li><a href="{% url 'messages_compose_to' transaction.seller.username %}">
            {{ transaction.seller }}
        </a></li>
    <li>정가 : {{ transaction.book.price }}</li>
    <li>판매가격 : {{transaction.sell_price }}원</li>
    <li><a href="{% url 'books:book_bucket_save' transaction.id %}">찜하기</a></li>
    <hr>
{% endfor %}

    </ul>

{% endblock %}