django_app/book_store/urls.py
from django.conf.urls import url

from . import views

app_name = 'books'
urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^sell/list$', views.book_sell_list, name='book_sell_list'),
    url(r'^sell/register$', views.book_sell_register, name='book_sell_register'),
    url(r'^sell/register/save$', views.book_sell_register_save, name='book_sell_register_save'),
    url(r'^bucket/(?P<transaction_pk>\d+)/save$', views.book_bucket_save, name='book_bucket_save'),
    url(r'^bucket/list$', views.book_bucket_list, name='book_bucket_list'),
    url(r'^buy/list$', views.book_buy_list, name='book_buy_list'),
    url(r'^book_search/$', views.book_search, name='book_search'),
    url(r'^book_bucket/$', views.book_bucket, name='book_bucket'),
    url(r'^detail/(?P<book_pk>\d+)/$', views.book_detail, name='book_detail'),

    url(r'^(?P<post_pk>\d+)/transaction/comment/$', views.transaction_comment_create, name='transaction_comment_create'),
]

django_app/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django_messages.views import *
from django_app.member.forms import NewComposeForm
# from member.forms import NewComposeForm
from django.conf.urls.static import static
from django_app.member import views
# from member import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^book/', include('book_store.urls', namespace="book_store")),
    url(r'^member/', include('member.urls', namespace="member")),
    url(r'^messages/compose/$', compose, {'form_class': NewComposeForm,}, name='messages_compose'),
    url(r'^messages/', include('django_messages.urls')),
    # url(r'^api-token-auth/', views.obtain_auth_token),
    url(r'^$', views.login),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)
urlpatterns += static('/static/', document_root='project/.static_root')
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_app/member/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from . import views


app_name = 'member'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),

    # social login
    url(r'^login/facebook/$', views.facebook_login, name='facebook_login'),
    url(r'^login/kakao/$', views.kakao_login, name='kakao_login'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

django_app/templates/common/base.html
{% load static %}

<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BookStore</title>

    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
    <!-- jQuery library -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
    <!-- Latest compiled JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->

    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/common.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Gochi Hand' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Walter Turncoat' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Seaweed Script' rel='stylesheet'>

</head>
<body>
    <div class="container">

        <div class="top-bar">
            <div class="do-it">
                <ul class='member-manager'>
                    <li>
                        <a href="{% url 'books:book_sell_list'%}">
                            판매중 책
                        </a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'member:profile'%}">
                            {{ user.nickname }}
                        </a>
                    </li>
                     <li>
                        <a href="{% url 'messages_inbox'%}">
                            쪽지함
                            {% if messages_inbox_count %}
                            new!
                            {% endif %}
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            장바구니
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'member:logout' %}">
                            로그아웃
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'member:login' %}">
                            로그인
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'member:signup' %}">
                            회원가입
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>

        <div class='top-wrap'>
            <div class='top-left'>
                <div class="home">
                    <a href="{% url 'books:main' %}">
                        bongdal
                    </a>
                </div>
            </div>
            <div class="top-center">
                <div class="search">
                    <ul>
                        <li>
                            <form action="{% url 'books:book_search' %}" method="POST" name="q">
                                {% csrf_token %}
                                {{ search }}
                                <button type="submit" class="btn-mint">검색</button>
                            </form>
                        </li>
                    </ul>
                    <!-- <nav class="navbar-default">
                        <ul class="nav navbar-nav entire-menu">
                            <li class="entire-menu-list">
                                <a href="#" class="a-element">베스트셀러</a>
                            </li>
                            <li class="entire-menu-list">
                                <a href="#" class="a-element">새로 등록된 상품</a>
                            </li>
                            <li class="entire-menu-list dropdown dropdown-large">
                                <a href="#" class="dropdown-toggle a-element" data-toggle="dropdown">카테고리 <b class="caret"></b></a>
                                {% include 'common/category.html' %}
                            </li>
                        </ul>
                    </nav> -->


                    <!--<ul>-->
                        <!--<li class="elements">-->
                            <!--<a href="#">베스트셀러</a>-->
                        <!--</li>-->
                        <!--<li class="elements">-->
                            <!--<a href="#">새로 등록된 상품</a>-->
                        <!--</li>-->
                        <!--<li class="elements">-->
                            <!--<a href="#">-->
                                <!--카테고리-->
                                <!--<img src="{% static 'images/arrow-down.png' %}" width="12px">-->
                            <!--</a>-->
                        <!--</li>-->
                    <!--</ul>-->
                </div>
            </div>
            <div class='top-right'>
                <img src="{% static 'images/logo.jpg' %}">
            </div>
        </div>
        {% block sidebar %}
        {% endblock %}
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

django_app/templates/common/category.html
<ul class="dropdown-menu dropdown-menu-large">
    <li class="">
        <ul>
            <li><a href="#">소설</a></li>
            <li><a href="#">시/에세이</a></li>
            <li><a href="#">경제/경영</a></li>
            <li><a href="#">자기계발</a></li>

            <li class="hr"><hr noshade /></li>

            <li><a href="#">인문</a></li>
            <li><a href="#">역사문화</a></li>
            <li><a href="#">종교</a></li>
            <li><a href="#">정치/사회</a></li>
            <li><a href="#">에술/대중문화</a></li>
            <li><a href="#">과학</a></li>
            <li><a href="#">기술/공학</a></li>
            <li><a href="#">컴퓨터/IT</a></li>
            <li class="hr"><hr noshade /></li>

            <li><a href="#">여행/기행</a></li>
            <li><a href="#">요리</a></li>
            <li><a href="#">만화</a></li>
        </ul>
    </li>
</ul>